steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['install']

  # Build the Next.js application
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    secretEnv: ['MONGODB_URI', 'AUTH_URL', 'AUTH_SECRET', 'GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET']

  # Copy static files to standalone directory
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp -r public .next/standalone/ 2>/dev/null || true
        mkdir -p .next/standalone/.next
        cp -r .next/static .next/standalone/.next/

  # Generate app.yaml with secrets injected
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cat > app.yaml <<EOF
        runtime: nodejs20
        instance_class: F2

        entrypoint: node .next/standalone/server.js

        env_variables:
          PORT: "8080"
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: "1"
          MONGODB_URI: "$$MONGODB_URI"
          AUTH_URL: "$$AUTH_URL"
          AUTH_SECRET: "$$AUTH_SECRET"
          GOOGLE_CLIENT_ID: "$$GOOGLE_CLIENT_ID"
          GOOGLE_CLIENT_SECRET: "$$GOOGLE_CLIENT_SECRET"


        automatic_scaling:
          min_instances: 0
          max_instances: 2
          target_cpu_utilization: 0.65

        handlers:
          - url: /_next/static
            static_dir: .next/static

          - url: /public
            static_dir: public

          - url: /.*
            script: auto
            secure: always
        EOF
    secretEnv: ['MONGODB_URI', 'AUTH_URL', 'AUTH_SECRET', 'GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET']

  # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['app', 'deploy', '--quiet', '--project=sturdy-gamma-481722-c8']

timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/sturdy-gamma-481722-c8/secrets/MONGODB_URI/versions/latest
      env: 'MONGODB_URI'
    - versionName: projects/sturdy-gamma-481722-c8/secrets/AUTH_URL/versions/latest
      env: 'AUTH_URL'
    - versionName: projects/sturdy-gamma-481722-c8/secrets/AUTH_SECRET/versions/latest
      env: 'AUTH_SECRET'
    - versionName: projects/sturdy-gamma-481722-c8/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: 'GOOGLE_CLIENT_ID'
    - versionName: projects/sturdy-gamma-481722-c8/secrets/GOOGLE_CLIENT_SECRET/versions/latest
      env: 'GOOGLE_CLIENT_SECRET'
